### ISSUE TITLE
Please add a new Readme with the instruction on how can one contribute to it

### ISSUE THREAD

**Issue by abhinav-193** [abhinav-193/Codes#23]

**Comment by vishakha868** [comment]
No one assigned

**Comment by abhinav-193** [comment]
> No one assigned

Yes do you want me to assign it to you?

**Comment by RohanTheProgrammer** [comment]
I am trying to do it

**Comment by vishakha868** [comment]
> > No one assigned
> 
> Yes do you want me to assign it to you?
yes pls

**Comment by RohanTheProgrammer** [comment]
#25 I have done a PR. Please check
