### ISSUE TITLE
Add more standard programs in C and C++

### ISSUE THREAD

**Issue by abhinav-193** [abhinav-193/Codes#5]

**Comment by Agung-Krisna** [comment]
I would like to add a linear search program if you allow me to

**Comment by Heman13557** [comment]
@abhinav-193  I would request you to add hacktoberfest label to your repo also because after new changes from hacktoberfest, Prs to your repo are not considered under that.
Would be great if you could do so.

**Comment by RahulRS246** [comment]
i would like to add mergesort

**Comment by NEENA-XAVIER** [comment]
I'll add bubble sort!

**Comment by abhinav-193** [comment]
@Heman13557 I have updated with the label thank you

**Comment by abhinav-193** [comment]
> @abhinav-193 I would request you to add hacktoberfest label to your repo also because after new changes from hacktoberfest, Prs to your repo are not considered under that. Would be great if you could do so.

Done
